[global]
backend=TensorRT
logging=yes
[slot_1]
profile_name=New Profile
chain_1_min_resolution=0x0
chain_1_max_resolution=0x0
chain_1_min_fps=0
chain_1_max_fps=0
chain_1_model_1_resize_height_before_upscale=0
chain_1_model_1_resize_factor_before_upscale=100
chain_1_model_1_name=2x_AnimeJaNai_SD_V1beta34_Compact
chain_1_rife=no
chain_1_rife_model=426
chain_1_rife_factor_numerator=2
chain_1_rife_factor_denominator=1
chain_1_rife_scene_detect_threshold=0.150
chain_1_rife_ensemble=no
[slot_2]
profile_name=force sd
chain_1_min_resolution=0x0
chain_1_max_resolution=0x0
chain_1_min_fps=0
chain_1_max_fps=0
chain_1_model_1_resize_height_before_upscale=0
chain_1_model_1_resize_factor_before_upscale=100
chain_1_model_1_name=2x_Compact_OTF_sd34testfinal8fixedmilestones_net_g_ema_250000
chain_1_rife=no
chain_1_rife_model=426
chain_1_rife_factor_numerator=2
chain_1_rife_factor_denominator=1
chain_1_rife_scene_detect_threshold=0.150
chain_1_rife_ensemble=no
[slot_3]
profile_name=bhiotf
chain_1_min_resolution=0x0
chain_1_max_resolution=0x0
chain_1_min_fps=0
chain_1_max_fps=0
chain_1_model_1_resize_height_before_upscale=0
chain_1_model_1_resize_factor_before_upscale=100
chain_1_model_1_name=2x_bhi_otf_batch64_gan_ArtCNN_R5F48_finetuneanimejanaisd34otf_25k_fp16_op17
chain_1_rife=no
chain_1_rife_model=426
chain_1_rife_factor_numerator=2
chain_1_rife_factor_denominator=1
chain_1_rife_scene_detect_threshold=0.150
chain_1_rife_ensemble=no
[slot_4]
profile_name=ArtCNN_R8F64_DS
chain_1_min_resolution=0x0
chain_1_max_resolution=0x0
chain_1_min_fps=0
chain_1_max_fps=0
chain_1_model_1_resize_height_before_upscale=0
chain_1_model_1_resize_factor_before_upscale=100
chain_1_model_1_name=ArtCNN_R8F64_DS
chain_1_rife=no
chain_1_rife_model=426
chain_1_rife_factor_numerator=2
chain_1_rife_factor_denominator=1
chain_1_rife_scene_detect_threshold=0.150
chain_1_rife_ensemble=no
[slot_5]
profile_name=sdspan
chain_1_min_resolution=0x0
chain_1_max_resolution=0x0
chain_1_min_fps=0
chain_1_max_fps=0
chain_1_model_1_resize_height_before_upscale=0
chain_1_model_1_resize_factor_before_upscale=100
chain_1_model_1_name=2x_animejanaisd34_otf_gan_lq192_batch8x4_oldloss_oldlrmilestones_SPAN_S_finetuneuniv1_7403_net_g_ema_120000-fp16-opset17
chain_1_rife=no
chain_1_rife_model=426
chain_1_rife_factor_numerator=2
chain_1_rife_factor_denominator=1
chain_1_rife_scene_detect_threshold=0.150
chain_1_rife_ensemble=no
[slot_6]
profile_name=rahxephon pre 600p
chain_1_min_resolution=0x0
chain_1_max_resolution=0x0
chain_1_min_fps=0
chain_1_max_fps=0
chain_1_model_1_resize_height_before_upscale=600
chain_1_model_1_resize_factor_before_upscale=100
chain_1_model_1_name=2x_Compact_OTF_sd34testfinal8fixedmilestones_net_g_ema_250000
chain_1_rife=no
chain_1_rife_model=426
chain_1_rife_factor_numerator=2
chain_1_rife_factor_denominator=1
chain_1_rife_scene_detect_threshold=0.150
chain_1_rife_ensemble=no
[slot_7]
profile_name=fdat m
chain_1_min_resolution=0x0
chain_1_max_resolution=0x0
chain_1_min_fps=0
chain_1_max_fps=0
chain_1_model_1_resize_height_before_upscale=0
chain_1_model_1_resize_factor_before_upscale=100
chain_1_model_1_name=2x_IllustrationJaNai_V3detail_FDAT_M_unshuffle_40k_fp16_fp16_op22
chain_1_rife=no
chain_1_rife_model=426
chain_1_rife_factor_numerator=2
chain_1_rife_factor_denominator=1
chain_1_rife_scene_detect_threshold=0.150
chain_1_rife_ensemble=no
[slot_8]
profile_name=New Profile
[slot_9]
profile_name=dat2
chain_1_min_resolution=0x0
chain_1_max_resolution=640x480
chain_1_min_fps=0
chain_1_max_fps=0
chain_1_model_1_resize_height_before_upscale=0
chain_1_model_1_resize_factor_before_upscale=100
chain_1_model_1_name=2x_bndl_animefilm_v1_DAT2_1x3xHxW_dyn-HW_fp32_op23_dynamo
chain_1_rife=no
chain_1_rife_model=426
chain_1_rife_factor_numerator=2
chain_1_rife_factor_denominator=1
chain_1_rife_scene_detect_threshold=0.150
chain_1_rife_ensemble=no